FROM mariadb:latest
ENV apt="git"
ENV git_url="https://github.com/matiasgonzalocalvo"
ENV challenge="ChallengeMercadoLibre3"
env python_challenge="challenge3.py"
RUN apt update ; apt install -y ${apt}
RUN git clone ${git_url}/${challenge}
WORKDIR ${challenge}
COPY mysql/*.sql /docker-entrypoint-initdb.d/
